const projects = [
  {
    name: "Real IOT Dashboard",
    description: "",
    image: "/projects/1.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["React", "Tailwind", "ChartJS", "Zustand"],
    bgColor: "6A4C93",
    textColor: "",
  },
  {
    name: "Wordle Game",
    description: "",
    image: "/projects/2.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["HTML", "CSS", "JavaScript"],
    bgColor: "1738BA",
    textColor: "",
  },
  {
    name: "Food Order App",
    description: "",
    image: "/projects/3.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["React", "Tailwind", "Zustand"],
    bgColor: "E17100",
    textColor: "",
  },
  {
    name: "Landing Page",
    description: "",
    image: "/projects/4.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["React", "Tailwind", "Zustand"],
    bgColor: "6CC4CC",
    textColor: "",
  },
  {
    name: "Bus Routes App",
    description: "",
    image: "/projects/5.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["React", "Tailwind", "Zustand"],
    bgColor: "174DB6",
    textColor: "",
  },
  {
    name: "IOT Dashboard",
    description: "",
    image: "/projects/6.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["React", "Tailwind", "Zustand"],
    bgColor: "D0D8C3",
    textColor: "",
  },
  {
    name: "Starbucks Clone",
    description: "",
    image: "/projects/7.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["Astro", "Tailwind"],
    bgColor: "006E49",
    textColor: "",
  },
  {
    name: "Product Design",
    description: "",
    image: "/projects/8.png",
    github: "https://",
    link: "https://",
    dowload: false,
    downlaodLink: "#",
    stack: ["Canva"],
    bgColor: "24356E",
    textColor: "",
  },
];

const history = [
  {
    year: "2024",
    role: "Full Stack Developer",
    description:
      "Led integration of home automation systems using KNX, SCADA, and WebSockets; developed ReactJS dashboards and UI/UX with Figma for real-time control.",
  },
  {
    year: "2024",
    role: "Web Consultant",
    description:
      "Advised on WordPress architecture, optimizing content, authentication, and payments; trained staff to improve platform management and internal processes.",
  },
  {
    year: "2023",
    role: "Web Provider",
    description:
      "Maintained and optimized a WordPress site; created an interactive ReactJS product catalog with over 1,000 items to enhance performance and accessibility.",
  },
  {
    year: "2021",
    role: "Electronic Engineering",
    description:
      "Currently in the 8th semester, specializing in automation, embedded systems, and control engineering, with a focus on applied electronics and system integration.",
  },
];

export default { projects, history };
